# Generated by Django 4.1.7 on 2023-03-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
