# Generated by Django 4.1.7 on 2023-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_orderitem_user_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
    ]
